merge workflows

diff --git a/.github/workflows/integrational-tests-unisocket.yml b/.github/workflows/integrational-tests-unisocket.yml
--- a/.github/workflows/integrational-tests-unisocket.yml
+++ b/.github/workflows/integrational-tests-unisocket.yml
@@ -153,7 +153,13 @@ jobs:
 
         cat output-python.txt | grep 'Successful connection!' -q
 
-    - name: Delete GKE cluster
-      if: ${{ always() }}
+    # Clean up
+    - name: Delete cluster
       run: |-
-        gcloud container clusters delete "${{inputs.cluster_name}}" --zone="$GKE_ZONE" --quiet
+        gcloud container clusters delete "$clusterName" --zone="$GKE_ZONE" --quiet
+
+    - name: Clean up of failure
+      if: ${{ failure() }}
+      run: |-
+        gcloud container clusters delete "$clusterName" --zone="$GKE_ZONE" --quiet
+        exit 1
